DELETE http://localhost:8082/users/659e4b28d790d29a27bb0662
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhdmtvc3RvdWRhc0BnbWFpbC5jb20iLCJleHAiOjE3MDQ4Nzk4NDIsInVzZXJJZCI6IjY1OWJmNGI1MDEzZmQ4OGYwODQxYTFjOSJ9.6N2YYxBJS0eFGCPz00V9E1o32Pexgqvu6waoI5nZBHs
