DELETE http://localhost:8082/users/deleteAll
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGUxMkBnbWFpbC5jb20iLCJleHAiOjE3MDQ4ODE2MjUsInVzZXJJZCI6IjY1OWU1MWI0OGQwY2Q4YjA2MzRhZDQ5ZiJ9.OsJ466mtf2Tgc86cJb3HJ3lu1Odf4FUxoRDv9kmqG1A
