GET http://localhost:8082/categoriesLicenses/count
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhdmtvc3RvdWRhc0BnbWFpbC5jb20iLCJleHAiOjE3MDUxNDEzODAsInVzZXJJZCI6IjY1YTBmNjE4OTg5NDUzMTY2NjAwYjQ1YiJ9._jg5PUM-HB4GRU38cY1_PQDju1kwcqcSdP36MZAbUEs