GET http://localhost:8082/categoriesLicenses/getMostRecent?created_dtFrom=2024-01-13 10:30:52&created_dtTo=2024-01-13 11:30:00&limit=1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhdmtvc3RvdWRhc0BnbWFpbC5jb20iLCJleHAiOjE3MDUxNDg4MjIsInVzZXJJZCI6IjY1YTBmNjE4OTg5NDUzMTY2NjAwYjQ1YiJ9.pVVGje7zQzDwW9iI4IH-vapGEji7OyEzW2NGRt2pilU