GET http://localhost:8082/licenses/countPerCategory?created_dtFrom=2024-01-15 10:00:00
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhdmtvc3RvdWRhc0BnbWFpbC5jb20iLCJleHAiOjE3MDU2ODEwNDAsInVzZXJJZCI6IjY1YTBmNjE4OTg5NDUzMTY2NjAwYjQ1YiJ9.mUSN1E59Xs3U4OybFXg5LpXxS9aALouDKbRm3ZIl5ns
