DELETE http://localhost:8082/licenses/65a51b99915d4b8a2efa3d49
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhdmtvc3RvdWRhc0BnbWFpbC5jb20iLCJleHAiOjE3MDU1NzAzNjksInVzZXJJZCI6IjY1YTBmNjE4OTg5NDUzMTY2NjAwYjQ1YiJ9.Iobd1xALvIamHD0x8E33W9Vgwt-1rpmy_nlpoZuBQD8
