GET http://localhost:8082/licenses/65a4eb5a1262b97a6c2175df
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhdmtvc3RvdWRhc0BnbWFpbC5jb20iLCJleHAiOjE3MDUzMTExNDAsInVzZXJJZCI6IjY1YTBmNjE4OTg5NDUzMTY2NjAwYjQ1YiJ9.DeOEAzDjRHcHsbQtuOvDpyC7HAk9Vr4lZyP-f2t9Ie8